# Generated by Django 5.1.3 on 2024-12-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futbolista',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='futbolista',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
